# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Agent",
    "SimulationSettings",
    "run_simulation",
]

@typing.final
class Agent:
    @property
    def current_area(self) -> builtins.float: ...
    @current_area.setter
    def current_area(self, value: builtins.float) -> None: ...
    @property
    def force_area(self) -> builtins.float: ...
    @force_area.setter
    def force_area(self, value: builtins.float) -> None: ...
    @property
    def force_perimeter(self) -> builtins.float: ...
    @force_perimeter.setter
    def force_perimeter(self, value: builtins.float) -> None: ...
    @property
    def force_dist(self) -> builtins.float: ...
    @force_dist.setter
    def force_dist(self, value: builtins.float) -> None: ...
    @property
    def min_dist(self) -> builtins.float: ...
    @min_dist.setter
    def min_dist(self, value: builtins.float) -> None: ...
    @property
    def target_area(self) -> builtins.float: ...
    @target_area.setter
    def target_area(self, value: builtins.float) -> None: ...
    @property
    def target_perimeter(self) -> builtins.float: ...
    @target_perimeter.setter
    def target_perimeter(self, value: builtins.float) -> None: ...
    @property
    def damping(self) -> builtins.float: ...
    @damping.setter
    def damping(self, value: builtins.float) -> None: ...
    @property
    def diffusion_constant(self) -> builtins.float: ...
    @diffusion_constant.setter
    def diffusion_constant(self, value: builtins.float) -> None: ...
    @property
    def position(self) -> builtins.list[builtins.float]: ...
    @position.setter
    def position(self, value: builtins.list[builtins.float]) -> None: ...
    def __new__(cls, position: numpy.typing.NDArray[numpy.float64], force_area: builtins.float, force_perimeter: builtins.float, target_area: builtins.float, force_dist: builtins.float, min_dist: builtins.float, target_perimeter: builtins.float, damping: builtins.float, diffusion_constant: builtins.float) -> Agent: ...

@typing.final
class SimulationSettings:
    r"""
    Contains settings needed to specify the simulation
    """
    @property
    def domain_size(self) -> builtins.float:
        r"""
        Overall domain size
        """
    @domain_size.setter
    def domain_size(self, value: builtins.float) -> None:
        r"""
        Overall domain size
        """
    @property
    def n_voxels(self) -> builtins.int:
        r"""
        Number of voxels to create subdivisions
        """
    @n_voxels.setter
    def n_voxels(self, value: builtins.int) -> None:
        r"""
        Number of voxels to create subdivisions
        """
    @property
    def dt(self) -> builtins.float:
        r"""
        Time increment used to solve the simulation
        """
    @dt.setter
    def dt(self, value: builtins.float) -> None:
        r"""
        Time increment used to solve the simulation
        """
    @property
    def t_max(self) -> builtins.float:
        r"""
        Maximum duration of the simulation
        """
    @t_max.setter
    def t_max(self, value: builtins.float) -> None:
        r"""
        Maximum duration of the simulation
        """
    @property
    def save_interval(self) -> builtins.float:
        r"""
        Frequency to store results
        """
    @save_interval.setter
    def save_interval(self, value: builtins.float) -> None:
        r"""
        Frequency to store results
        """
    @property
    def rng_seed(self) -> builtins.int:
        r"""
        Random initial seed
        """
    @rng_seed.setter
    def rng_seed(self, value: builtins.int) -> None:
        r"""
        Random initial seed
        """
    @property
    def approximation_steps(self) -> builtins.int:
        r"""
        Steps to take to approximate the size of the cell
        """
    @approximation_steps.setter
    def approximation_steps(self, value: builtins.int) -> None:
        r"""
        Steps to take to approximate the size of the cell
        """
    def __new__(cls) -> SimulationSettings:
        r"""
        Creates a new :class:`SimulationSettings` class.
        """

def run_simulation(settings: SimulationSettings, agents: typing.Sequence[Agent]) -> builtins.dict[builtins.int, builtins.list[tuple[builtins.list[builtins.float], builtins.list[tuple], builtins.float]]]:
    r"""
    Performs a complete numerical simulation of our system.
    
    Args:
        simulation_settings(SimulationSettings): The settings required to run the simulation
    """

