# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
import os
import pathlib
import typing
__all__ = [
    "Agent",
    "Fungus",
    "PlantCell",
    "SimulationSettings",
    "find_results",
    "get_all_iterations",
    "load_all_results",
    "load_results",
    "run_simulation",
]

@typing.final
class Fungus:
    @property
    def position(self) -> numpy.typing.NDArray[numpy.float64]: ...
    @position.setter
    def position(self, value: numpy.typing.NDArray[numpy.float64]) -> None: ...
    @property
    def radius(self) -> builtins.float: ...
    def __new__(cls, pos: numpy.typing.NDArray[numpy.float64], diffusion_constant: builtins.float, spring_tension: builtins.float, rigidity: builtins.float, spring_length: builtins.float, damping: builtins.float, radius: builtins.float, potential_stiffness: builtins.float, cutoff: builtins.float, strength: builtins.float) -> Fungus: ...

@typing.final
class PlantCell:
    @property
    def force_area(self) -> builtins.float: ...
    @force_area.setter
    def force_area(self, value: builtins.float) -> None: ...
    @property
    def force_perimeter(self) -> builtins.float: ...
    @force_perimeter.setter
    def force_perimeter(self, value: builtins.float) -> None: ...
    @property
    def force_dist(self) -> builtins.float: ...
    @force_dist.setter
    def force_dist(self, value: builtins.float) -> None: ...
    @property
    def force_angle(self) -> builtins.float: ...
    @force_angle.setter
    def force_angle(self, value: builtins.float) -> None: ...
    @property
    def interaction_range(self) -> builtins.float: ...
    @interaction_range.setter
    def interaction_range(self, value: builtins.float) -> None: ...
    @property
    def min_dist(self) -> builtins.float: ...
    @min_dist.setter
    def min_dist(self, value: builtins.float) -> None: ...
    @property
    def target_area(self) -> builtins.float: ...
    @target_area.setter
    def target_area(self, value: builtins.float) -> None: ...
    @property
    def target_perimeter(self) -> builtins.float: ...
    @target_perimeter.setter
    def target_perimeter(self, value: builtins.float) -> None: ...
    @property
    def damping(self) -> builtins.float: ...
    @damping.setter
    def damping(self, value: builtins.float) -> None: ...
    @property
    def diffusion_constant(self) -> builtins.float: ...
    @diffusion_constant.setter
    def diffusion_constant(self, value: builtins.float) -> None: ...
    @property
    def position(self) -> numpy.typing.NDArray[numpy.float64]: ...
    @position.setter
    def position(self, value: numpy.typing.NDArray[numpy.float64]) -> None: ...
    def __new__(cls, position: numpy.typing.NDArray[numpy.float64], force_area: builtins.float, force_perimeter: builtins.float, target_area: builtins.float, force_angle: builtins.float, force_dist: builtins.float, interaction_range: builtins.float, min_dist: builtins.float, target_perimeter: builtins.float, damping: builtins.float, diffusion_constant: builtins.float) -> PlantCell: ...
    def get_perimeter(self) -> builtins.float: ...
    def get_area(self) -> builtins.float: ...

@typing.final
class SimulationSettings:
    r"""
    Contains settings needed to specify the simulation
    """
    @property
    def domain_size(self) -> builtins.float:
        r"""
        Overall domain size
        """
    @domain_size.setter
    def domain_size(self, value: builtins.float) -> None:
        r"""
        Overall domain size
        """
    @property
    def domain_force_dist(self) -> builtins.float: ...
    @domain_force_dist.setter
    def domain_force_dist(self, value: builtins.float) -> None: ...
    @property
    def domain_interaction_range(self) -> builtins.float: ...
    @domain_interaction_range.setter
    def domain_interaction_range(self, value: builtins.float) -> None: ...
    @property
    def n_voxels(self) -> builtins.int:
        r"""
        Number of voxels to create subdivisions
        """
    @n_voxels.setter
    def n_voxels(self, value: builtins.int) -> None:
        r"""
        Number of voxels to create subdivisions
        """
    @property
    def dt(self) -> builtins.float:
        r"""
        Time increment used to solve the simulation
        """
    @dt.setter
    def dt(self, value: builtins.float) -> None:
        r"""
        Time increment used to solve the simulation
        """
    @property
    def t_max(self) -> builtins.float:
        r"""
        Maximum duration of the simulation
        """
    @t_max.setter
    def t_max(self, value: builtins.float) -> None:
        r"""
        Maximum duration of the simulation
        """
    @property
    def save_interval(self) -> builtins.float:
        r"""
        Frequency to store results
        """
    @save_interval.setter
    def save_interval(self, value: builtins.float) -> None:
        r"""
        Frequency to store results
        """
    @property
    def rng_seed(self) -> builtins.int:
        r"""
        Random initial seed
        """
    @rng_seed.setter
    def rng_seed(self, value: builtins.int) -> None:
        r"""
        Random initial seed
        """
    @property
    def perimeter_mod(self) -> builtins.float: ...
    @perimeter_mod.setter
    def perimeter_mod(self, value: builtins.float) -> None: ...
    def __new__(cls) -> SimulationSettings:
        r"""
        Creates a new :class:`SimulationSettings` class.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Agent(enum.Enum):
    P = ...
    F = ...

def find_results(settings: SimulationSettings) -> typing.Optional[pathlib.Path]: ...

def get_all_iterations(path: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[builtins.int]: ...

def load_all_results(path: builtins.str | os.PathLike | pathlib.Path) -> builtins.dict[builtins.int, builtins.list[Agent]]: ...

def load_results(iteration: builtins.int, path: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[Agent]: ...

def run_simulation(settings: SimulationSettings, agents: typing.Sequence[typing.Any]) -> pathlib.Path:
    r"""
    Performs a complete numerical simulation of our system.
    
    Args:
        simulation_settings(SimulationSettings): The settings required to run the simulation
    """

