on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'false'
      - name: Install libfontconfig1-dev
        if: ${{ contains(inputs.os, 'ubuntu') }}
        run: sudo apt-get install libfontconfig1-dev

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Check
        run: cargo check

      - name: DocTest
        run: cargo test --doc

      - name: Test MacOs
        if: ${{ contains(inputs.os, 'macos') }}
        run: cargo test --workspace --exclude cellular_raza-template-pyo3
      - name: Test
        if: ${{ !contains(inputs.os, 'macos') }}
        run: cargo test
